services:
  db:
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: password
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
  springtest:
    image: springtestgoo
    restart: always
    ports:
      - 8080:8080