spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springtest
    username: root
    password:
    class_driver: com.mysql.jdbc.Driver
  #    driverClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      #        ddl-auto: update
      ddl-auto: create-drop
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.MySQL5Dialect

